require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :dynamic
end

target 'ReactNativeSampleApp' do
  use_frameworks! :linkage => :dynamic
  config = use_native_modules!
 

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ReactNativeSampleAppTests' do
    inherit! :complete
    # Pods for testing
  end

 post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                  config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
              end
 	case target.name
  		when 'RCT-Folly'
    		target.build_configurations.each do |config|
      		config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    		end
  	end
          end
      end
  end
end
$static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
        'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
        'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
        'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native','React-logger','RCT-Folly','React-jsi','React-cxxreact','React-jsiexecutor','React-hermes','React-Core','RCTTypeSafety','RNGestureHandler','React-RCTText','react-native-safe-area-context','ReactCommon','React-RCTAppDelegate','React-Codegen','React-RCTVibration','React-RCTSettings','React-RCTLinking','React-RCTNetwork','React-RCTAnimation','React-RCTBlob','React-RCTImage','React-CoreModules','RNScreens']
    pre_install do |installer|
        Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
        installer.pod_targets.each do |pod|
            if $static_framework.include?(pod.name)
              def pod.build_type;
                Pod::BuildType.static_library
              end
            end
          end
    end

