# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EnxRtcSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EnxRtcSample

   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network/React-RCTNetwork.podspec'
  
   pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules/React-CoreModules.podspec'
  
   pod 'enx-rtc-react-native', :path => '../node_modules/enx-rtc-react-native/ios/RNEnxRtc.podspec'
  
   pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
   
  
  #pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket/React-RCTWebSocket.podspec'
  
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS/React-RCTLinking.podspec'
  
   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration/React-RCTVibration.podspec'
   
    pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text/React-RCTText.podspec'
    
    pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings/React-RCTSettings.podspec'
     
      pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image/React-RCTImage.podspec'
      pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
      
#       pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob/React-RCTBlob.podspec'
       pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
       
       pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec'
       
       pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
       pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector'
       
       pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired'
       
       pod 'ReactCommon/turbomodule/core', :path => '../node_modules/react-native/ReactCommon'
       pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
       pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
       pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
       pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
       
       pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS/React-RCTActionSheet.podspec'
       
        pod 'React', :path => '../node_modules/react-native/React.podspec' 
       
       pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
        
          pod 'ReactNativeNavigation', :podspec => '../node_modules/react-native-navigation/ReactNativeNavigation.podspec'
  #use_unimodules!

  

end


